#+TITLE: Bytecoin Notes
* Description
- Each Bytelandian gold coin has an integer number written on it.
- A coin n can be exchanged in a bank into three coins: n/2, n/3 and n/4. But these numbers are all rounded down (the banks have to make a profit).
- You can also sell Bytelandian coins for American dollars. The exchange rate is 1:1. But you can not buy Bytelandian coins.
- You have one gold coin. What is the maximum amount of American dollars you can get for it?
- Input
    The input will contain several test cases (not more than 10). Each testcase is a single line with a number n, 0 <= n <= 1 000 000 000. It is the number written on your coin.
- Output
    For each test case output a single line, containing the maximum amount of American dollars you can make.
    Example
    Input:
    12
    2
    Output:
    13
    2
    You can change 12 into 6, 4 and 3, and then change these into $6+$4+$3 = $13. If you try changing the coin 2 into 3 smaller coins, you will get 1, 0 and 0, and later you can get no more than $1 out of them. It is better just to change the 2 coin directly into $2.
* Table
|  n |                         |   |
|  0 | 0/2 + 0/3 + 0/4 = 0     |   |
|  1 | 1/2 + 1/3 + 1/4 = 0     |   |
|  2 | 2/2 + 2/3 + 2/4 = 1     |   |
|  3 | 3/2 + 3/3 + 3/4 = 2     |   |
|  4 | 4/2 + 4/3 + 4/4 = 4     |   |
|  5 | 5/2 + 5/3 + 5/4 = 4     |   |
|  6 | 6/2 + 6/3 + 6/4 = 6     |   |
|  7 | 7/2 + 7/3 + 7/4 = 6     |   |
|  8 | 8/2 + 8/3 + 8/4 = 8     |   |
|  9 | 9/2 + 9/3 + 9/4 = 9     |   |
| 10 | 10/2 + 10/3 + 10/4 = 10 |   |
| 11 | 11/2 + 11/3 + 11/4 = 10 |   |
| 12 | 12/2 + 12/3 + 12/4 = 13 |   |
